### ISSUE TITLE
我收到錯誤

### ISSUE THREAD

**Issue by xSalved** [zmzimpl/auto-friend#2]
我收到錯誤。你能幫助我嗎？
![image](https://github.com/zmzimpl/auto-friend/assets/107212790/f5c48dfa-e3b2-448f-940f-9f201509f3da)

**Comment by xSalved** [comment]
我在 cmd 上得到了正確的“privacy:token”，但它不起作用

**Comment by zmzimpl** [comment]
> 我在 cmd 上得到了正確的“privacy:token”，但它不起作用

有没有进行加密？默认代码里面是需要经过加密的，你可以截图你的 wallets.json 打码我看看

**Comment by zmzimpl** [comment]
> 我在 cmd 上得到了正確的“privacy:token”，但它不起作用

这个错误表明你设置的 `authorization` 没有起效果，如果你已经使用 utils/encrypt.js 加密了，看下是否是双引号等一些细节的问题

**Comment by xSalved** [comment]
![image](https://github.com/zmzimpl/auto-friend/assets/107212790/a5d13cca-2ba0-4993-a452-f23838316ce0)

**Comment by xSalved** [comment]
這是正確的“授權”字段
![image](https://github.com/zmzimpl/auto-friend/assets/107212790/db9be7a2-f3a1-4d24-8073-6fd6a8fbfb58)

**Comment by zmzimpl** [comment]
> 這是正確的“授權”字段 ![image](https://user-images.githubusercontent.com/107212790/268335537-db9be7a2-f3a1-4d24-8073-6fd6a8fbfb58.png)

抱歉，我确认了一下，应该是请求头信息无法通用的问题，明天我会给出解决方案

**Comment by zmzimpl** [comment]
> 這是正確的“授權”字段 ![image](https://user-images.githubusercontent.com/107212790/268335537-db9be7a2-f3a1-4d24-8073-6fd6a8fbfb58.png)

你可以在 Network 复制自己的请求头，也可以等我给出解决方法

**Comment by zmzimpl** [comment]
<img width="420" alt="1694795922868" src="https://github.com/zmzimpl/auto-friend/assets/27490895/2cee5bc9-0139-4bbd-b5fb-4a7075eb063b">

具体请求头的方法，在 network 上找到 https://prod-api.kosetto.com/portfolio/xxx 接口，按照上图复制请求，将代码中的请求头替换，类似这样
![image](https://github.com/zmzimpl/auto-friend/assets/27490895/07bf1421-03fb-4fd4-af55-3d445b143734)

**Comment by xSalved** [comment]
thanks!

**Comment by zmzimpl** [comment]
#3 这个 pr 解决了这个问题
